on:
  workflow_dispatch:
    inputs:
      build_number:
        description: "Build number"
        required: true
        default: ""

name: Energeo CI on ECR

jobs:
  deploy_back:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Display build number
        run: echo "Deploying build ${{ github.event.inputs.build_number }} to dev"
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get color
        run: echo ${{ steps.login-ecr.outputs.registry }}

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 205816504133.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: energeo
        run: |
          # Build a docker container and push it to ECR 
          cd back
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.build_number }} .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.build_number }}
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.event.inputs.build_number }}"
